"""phase2_reconstruction_mass_celery_columns

Revision ID: 20005f3e071a
Revises: 
Create Date: 2026-03-16 09:01:13.409238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20005f3e071a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_event')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ingestion_source',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('reconstruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('low_quality_flag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('quality_warning', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('station_offsets_estimated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('mass_estimation_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('estimated_mass_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_mass_lower_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_mass_upper_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('luminous_efficiency_tau', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_reference_solution', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconstruction', schema=None) as batch_op:
        batch_op.drop_column('is_reference_solution')
        batch_op.drop_column('luminous_efficiency_tau')
        batch_op.drop_column('estimated_mass_upper_kg')
        batch_op.drop_column('estimated_mass_lower_kg')
        batch_op.drop_column('estimated_mass_kg')
        batch_op.drop_column('mass_estimation_available')
        batch_op.drop_column('station_offsets_estimated')
        batch_op.drop_column('quality_warning')
        batch_op.drop_column('low_quality_flag')
        batch_op.drop_column('celery_task_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('ingestion_source',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('_alembic_tmp_event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gmn_id', sa.VARCHAR(), nullable=True),
    sa.Column('network', sa.VARCHAR(length=6), nullable=False),
    sa.Column('begin_utc', sa.DATETIME(), nullable=False),
    sa.Column('end_utc', sa.DATETIME(), nullable=True),
    sa.Column('peak_abs_magnitude', sa.FLOAT(), nullable=True),
    sa.Column('entry_velocity_km_s', sa.FLOAT(), nullable=True),
    sa.Column('geocentric_velocity_km_s', sa.FLOAT(), nullable=True),
    sa.Column('radiant_ra_deg', sa.FLOAT(), nullable=True),
    sa.Column('radiant_dec_deg', sa.FLOAT(), nullable=True),
    sa.Column('begin_lat', sa.FLOAT(), nullable=True),
    sa.Column('begin_lon', sa.FLOAT(), nullable=True),
    sa.Column('begin_ht_km', sa.FLOAT(), nullable=True),
    sa.Column('end_lat', sa.FLOAT(), nullable=True),
    sa.Column('end_lon', sa.FLOAT(), nullable=True),
    sa.Column('end_ht_km', sa.FLOAT(), nullable=True),
    sa.Column('duration_sec', sa.FLOAT(), nullable=True),
    sa.Column('station_count', sa.INTEGER(), nullable=True),
    sa.Column('region', sa.VARCHAR(), nullable=True),
    sa.Column('shower_id', sa.INTEGER(), nullable=True),
    sa.Column('ingestion_source', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['shower_id'], ['shower.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
